version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/launchpadcentral/govalidator
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...

workflows:
  version: 2
  test-and-build:
    jobs:
      - build:
          context: org-global
